### ISSUE TITLE
User defined names as Comment in RFEM

### ISSUE THREAD

**Issue by staintono** [BHoM/RFEM6_Toolkit#21]
#### Description:

Pushing of User inputted Name parameter of sections/bars/materials/surface into the comments parameter in RFEM
![image](https://user-images.githubusercontent.com/62057195/235685298-eda08e30-7a01-4185-8ff0-0f21f727a2f7.png)

**Comment by HugoVanLooveren** [comment]
Would be pretty useful to have this!
