### ISSUE TITLE
RFEM_Adapter: Pulled Cross Sections do not own ID reference to material anymore

### ISSUE THREAD

**Issue by alelom** [BHoM/RFEM6_Toolkit#30]
#### Description:

When pulling/reading cross-sections from RFEM6, it's not possible to get the needed information about the assigned material. Initially, through a defined ID from the RFEM API, you could find the correct material. However, now all materials linked to a section seem to have an ID of 0, indicating they are undefined.

#### Steps to reproduce:

Grasshopper Steps: 
Create Steel or Concrete Sections/Beams in RFEM.
Pull the sections or beams

Occuring Error Message: 
![image](https://github.com/BHoM/RFEM6_Toolkit/assets/104030973/84163b94-a790-4542-8e3f-4afb76772ec5)

#### Expected behaviour:

Pulling and reading for Concrete and Steel (Sections) should work smoothly, at least for standard EU Sections/Materials.

#### Test file(s):

[gh file](https://burohappold-my.sharepoint.com/:u:/r/personal/arne_martensen_burohappold_com/Documents/bugExample0.gh?csf=1&web=1&e=hHJnnE)
[RFEM file](https://burohappold-my.sharepoint.com/:u:/r/personal/arne_martensen_burohappold_com/Documents/bugExample.rf6?csf=1&web=1&e=gxFIpVl)

**Comment by Arne-Martensen** [comment]
Issue was resolved by updateing the RFEMWebServiceLibrary to version 3.7. The Material ID is now attached to the section.
