### ISSUE TITLE
Additional load case for same action category (wind x,-x,y,-y)

### ISSUE THREAD

**Issue by cribellato** [BHoM/RFEM6_Toolkit#62]
Wind load case is only possible one time and is currently superimposing all directions, it is necessary to have at least 4 possibilities for wind load (wind x,-x,y,-y), which means 4 load cases with the same action category. 
It could/should be extended to other action categories.

[Test file](https://burohappold.sharepoint.com/:u:/s/BHoM/EZa5tRRdAeZImQZrB9NoL1QBthUK1Cy3pULq3VoZvj_s9g?e=ojQ6lu)

**Comment by staintono** [comment]
This could be solved with #42 by being able to push the loadcase name and number
